### ISSUE TITLE
Foot sliding and Rotation Mismatch on CMU Mocap Dataset

### ISSUE THREAD

**Issue by xjwxjw** [BartMoyaers/BvhToDeepMimic#5]
Hello, I tested your code on the CMU Mocap Dataset with all joint in ZYX order.
I find that there are noticeable foot sliding and rotation mismatch:
For 02_01.bvh (foot sliding):
![1](https://user-images.githubusercontent.com/23734975/63699152-dd77cc00-c852-11e9-94b3-6a1b24d13f23.gif)
For 13_01.bvh (rotation mismatch, the character should be straight all the time)
![2](https://user-images.githubusercontent.com/23734975/63699322-24fe5800-c853-11e9-9081-1d0de376aef8.gif)
I also provide the source bvh files for reference:
[bvh.tar.gz](https://github.com/BartMoyaers/BvhToDeepMimic/files/3541639/bvh.tar.gz)
Would you please help me with these issues? 
Thank you very much!

**Comment by BartMoyaers** [comment]
Hi xjwxjw, could you provide the website where you found the .bvh files? As well as the settings.json you used to generate these movements.

I just tried converting the files that you posted, but I don't get the same results.

**Comment by xjwxjw** [comment]
Sure, the website: http://www.cgspeed.com/ with the following link,
![1](https://user-images.githubusercontent.com/23734975/63765275-46b31a00-c8fb-11e9-80d6-be672d758957.png)
as well as settings.json:

[settings.json.tar.gz](https://github.com/BartMoyaers/BvhToDeepMimic/files/3545710/settings.json.tar.gz)

**Comment by xjwxjw** [comment]
I also change Line.251 in bvh_joint_handler.py as follows:
translation[1] -> translation[1] + 0.45.
It means I manually add a constant in the Y-axis direction. Because I find part of the character is under the ground.

**Comment by BartMoyaers** [comment]
With the same settings as you, but without the extra vertical offset you added I get the following result:
![ezgif com-crop](https://user-images.githubusercontent.com/43953552/63855987-f2fb0c00-c9a0-11e9-8ede-9f9dba90c09d.gif)

Its not perfect, the feet seem to be a little off, I should still look at the feet conversions in fact, they can be improved.

Also the model is floating a little off the ground. With the current implementation this is normal, because the proportion between the limbs in the BVH file is not taken into account. We simply hope that the limb proportions are going to be almost the same as the humanoid model from DeepMimic. With this BVH file this doesn't seem to be the case.

(The legs in the BVH file are longer than the legs of the DeepMimic model.)

**Comment by BartMoyaers** [comment]
The scale factor `"scale": 0.056444` in your settings file seems to be right.

> I also change Line.251 in bvh_joint_handler.py as follows:
> translation[1] -> translation[1] + 0.45.
> It means I manually add a constant in the Y-axis direction. Because I find part of the character is under the ground.

Perhaps you can try to lower the position of the model a little with the same method you described, should give a pretty good result.

**Comment by xjwxjw** [comment]
OK, thx, I understand the reason for foot sliding.
But the rotation mismatch still bothers me.
You can try 13_01.bvh directly on this website: http://lo-th.github.io/olympe/BVH_player.html.
If comparing this to the transformed one in deepmimic, you can find that the whole body of character is rotated during sitting down in deepmimic. 
While as visualized in http://lo-th.github.io/olympe/BVH_player.html, the whole body keeps straight all the time.
What is the possible reason for this part?

**Comment by BartMoyaers** [comment]
I've been looking into it, but didn't find a solution yet.
It seems like the 13_01.bvh file is a bit different than the .bvh files from [here.](http://mocap.cs.sfu.ca/). (Which this code is based on.)

Let me explain how to code works now, with the "correct" root links as in the files from SFU.
The original BVH files had the root links as follows:
![skeleton_root_problem](https://user-images.githubusercontent.com/43953552/64324724-29e7a800-cfc7-11e9-9eb0-2a268de735ef.png)

Their positions in relation to each other seem to be fixed, in the sense that all these links are positioned in a plane. This was (ab)used by me in order to calculate a correct root rotation frame in the following way: 
![text4604-9-0-8-4-3](https://user-images.githubusercontent.com/43953552/64325485-8ac3b000-cfc8-11e9-8110-f0cd54f81e75.png)
(z pointing up/towards you)

It's calculated in [these lines of code](https://github.com/BartMoyaers/BvhToDeepMimic/blob/ba6acf39a7bd5686921a9920f62cb4890f2184ba/bvhtodeepmimic/bvh_joint_handler.py#L170-L193). 

In the DeepMimic humanoid model, the legs and spine seem to be FIXED to the root in a similar fashion, that's why we are able to get quite good results in the conversions, as long as you use the SFU-style BVH files.

With the BVH files that you provided, the links around the root are not fixed. (The spine can rotate around the root for example.) This causes problems with the way it is calculated now.

**Comment by xjwxjw** [comment]
Thanks for detailed comments, I think you are right.
So I manually force these four points to form a rigid triangular, which seems not so bad, at least for some standing position.
